# Generated by Django 5.1.15 on 2026-06-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"ordering": ["-created_at"]},
        ),
    ]
